networks:
  back-net:

services:
  api:
    container_name: sql-api
    build:
      dockerfile: ./Dockerfile
      target: runtime
    env_file: .api.env
    networks:
      - back-net
    depends_on:
      postgres_api:
        condition: service_healthy
    ports:
      - 8000:8000
  
  postgres_api:
    container_name: postgres_api
    image: postgres:12.0-alpine
    env_file: .db.env
    expose: 
      - 5432
    networks:
      - back-net
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 5s
      retries: 3